const state={orders:[],selected:null};
const money=n=>`${Number(n||0).toFixed(2)} JOD`;
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const statusLabel=s=>({new:'New',confirmed:'Confirmed',out_for_delivery:'Out for Delivery',delivered:'Delivered',cancelled:'Cancelled'}[s]||s);
async function api(path,options={}){const r=await adminAuth.authFetch(`/rest/v1/${path}`,options);const data=await r.json().catch(()=>null);if(!r.ok)throw new Error(data?.message||data?.hint||`Request failed (${r.status})`);return data;}
async function loadOrders(){setMessage('Loading orders…');try{state.orders=await api('rpc/admin_list_orders');render();setMessage(state.orders.length?`${state.orders.length} order${state.orders.length===1?'':'s'} loaded.`:'No orders yet. New customer orders will appear here.');}catch(e){setMessage(`Could not load orders: ${e.message}`,'error');if(/401|403|not authorized/i.test(e.message)){adminAuth.clearSession();location.href='admin-login.html';}}}
function setMessage(text,type=''){const el=document.getElementById('orderMessage');if(el){el.textContent=text;el.style.color=type==='error'?'#a12626':'';}}
function render(){const q=(document.getElementById('orderSearch')?.value||'').toLowerCase().trim();const filter=document.getElementById('orderStatus')?.value||'all';const list=state.orders.filter(o=>(filter==='all'||o.status===filter)&&(!q||`${o.id} ${o.customer_name} ${o.customer_phone} ${o.customer_email}`.toLowerCase().includes(q)));document.getElementById('ordersBody').innerHTML=list.length?list.map(row).join(''):`<tr><td colspan="7"><div class="empty-orders">No orders match your filter.</div></td></tr>`;const count=s=>state.orders.filter(o=>o.status===s).length;document.getElementById('orderCount').textContent=state.orders.length;document.getElementById('newCount').textContent=count('new');document.getElementById('confirmedCount').textContent=count('confirmed');document.getElementById('deliveryCount').textContent=count('out_for_delivery');document.getElementById('deliveredCount').textContent=count('delivered');if(state.selected&&!state.orders.some(o=>o.id===state.selected))closeDetail();}
function row(o){const d=new Date(o.created_at);return `<tr class="order-click" onclick="openOrder('${esc(o.id)}')"><td><b>#${esc(o.id.slice(0,8).toUpperCase())}</b><br><span class="notes">${o.items?.length||0} line item${(o.items?.length||0)===1?'':'s'}</span></td><td><b>${esc(o.customer_name)}</b><br><span class="notes">${esc(o.customer_phone)}<br>${esc(o.customer_email)}</span></td><td>${esc(o.governorate)}<br><span class="notes">${esc(o.area)}</span></td><td><b>${money(o.total)}</b><br><span class="notes">Delivery: ${money(o.delivery)}</span></td><td>${esc(o.payment_method||'Cash on Delivery')}</td><td onclick="event.stopPropagation()"><select class="status-select" onchange="updateStatus('${esc(o.id)}',this.value)" aria-label="Order status">${['new','confirmed','out_for_delivery','delivered','cancelled'].map(s=>`<option value="${s}" ${o.status===s?'selected':''}>${statusLabel(s)}</option>`).join('')}</select></td><td>${d.toLocaleDateString()}<br><span class="notes">${d.toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}</span></td></tr>`;}
window.openOrder=id=>{const o=state.orders.find(x=>x.id===id);if(!o)return;state.selected=id;const box=document.getElementById('orderDetail');const items=Array.isArray(o.items)?o.items:[];box.innerHTML=`<div style="display:flex;justify-content:space-between;gap:15px;align-items:start"><div><div class="eyebrow">ORDER</div><h2>#${esc(o.id)}</h2></div><button class="btn btn-outline" onclick="closeDetail()">CLOSE</button></div><div class="order-grid"><div class="order-box"><h4>Customer</h4><p><b>${esc(o.customer_name)}</b></p><p>${esc(o.customer_phone)}</p><p>${esc(o.customer_email)}</p></div><div class="order-box"><h4>Delivery Address</h4><p>${esc(o.governorate)} — ${esc(o.area)}</p><p>${esc(o.street_address)}</p>${o.additional_details?`<p><b>Details:</b> ${esc(o.additional_details)}</p>`:''}</div></div><div class="order-box" style="margin-top:16px"><h4>Products</h4>${items.map(i=>`<div class="order-line"><span>${esc(i.name||i.id)} × ${Number(i.qty||1)}</span><b>${money(i.lineTotal)}</b></div>`).join('')}<div class="order-line"><span>Subtotal</span><b>${money(o.subtotal)}</b></div><div class="order-line"><span>Delivery</span><b>${money(o.delivery)}</b></div><div class="order-line" style="border:0;font-size:18px"><b>Total</b><b>${money(o.total)}</b></div><p class="notes">Payment: ${esc(o.payment_method||'Cash on Delivery')} · Status: ${esc(statusLabel(o.status))}</p></div>`;box.classList.add('open');};
window.closeDetail=()=>{state.selected=null;document.getElementById('orderDetail').classList.remove('open');};
window.updateStatus=async(id,status)=>{try{setMessage('Updating order…');const r=await api('rpc/admin_update_order_status',{method:'POST',body:JSON.stringify({p_order_id:id,p_status:status})});const idx=state.orders.findIndex(o=>o.id===id);if(idx>=0)state.orders[idx]=r;render();if(state.selected===id)openOrder(id);setMessage(`Order ${id.slice(0,8).toUpperCase()} updated to ${statusLabel(status)}.`);}catch(e){setMessage(`Could not update order: ${e.message}`,'error');await loadOrders();}};
document.addEventListener('DOMContentLoaded',async()=>{if(!(await adminAuth.verifyAdmin()))return;document.getElementById('orderSearch').addEventListener('input',render);document.getElementById('orderStatus').addEventListener('change',render);document.getElementById('refreshOrders').addEventListener('click',loadOrders);document.getElementById('logoutButton').addEventListener('click',async()=>{adminAuth.clearSession();location.href='admin-login.html';});loadOrders();});
