const DEFAULT_PRODUCTS=[
{id:'eros-najim',name:'Versace Eros Najim Parfum',price:null,priceLabel:'Price on request',category:'Men',notes:'Yellow Mandarin · Clary Sage · Saffron · Cardamom · Oud · Cedarwood · Caramel · Patchouli · Vetiver · Incense · Tonka',size:'100ml',stock:12,image:'https://www.triostore.com.tr/parfum/versace-eros-najim-100ml-parfum_1.jpg'},
{id:'dior-sauvage-edp',name:'Dior Sauvage Eau de Parfum',price:null,priceLabel:'Price on request',category:'Men',notes:'Bergamot · Vanilla · Patchouli · Spicy Citrus',size:'100ml',stock:12,image:'https://cdn.mart.ps/222439-thickbox_default/%D8%B9%D8%B7%D8%B1-%D8%B3%D9%88%D8%A7%D9%81%D8%A7%D8%AC-%D9%85%D9%86-%D8%AF%D9%8A%D9%88%D8%B1-%D9%84%D9%84%D8%B1%D8%AC%D8%A7%D9%84-%D8%B3%D8%B9%D8%A9-100-%D9%85%D9%84-sauvage-eau-de-parfum-edp-by-dior-for-men-100ml.jpg'},
{id:'versace-eros-edp',name:'Versace Eros Eau de Parfum',price:null,priceLabel:'Price on request',category:'Men',notes:'Lemon · Mandarin · Mint · Candied Apple · Geranium · Cedarwood · Vetiver · Patchouli · Sandalwood · Vanilla',size:'100ml',stock:12,image:'https://down-br.img.susercontent.com/file/sg-11134201-7rbk8-lqe63odwmwjpe2'},
{id:'stronger-you-intensely',name:'Stronger With You Intensely',price:null,priceLabel:'Price on request',category:'Men',notes:'Vanilla · Amber · Spices',size:'100ml',stock:12,image:'https://manzara-eg.com/cdn/shop/files/stronger-with-you-intensely-by-giorgio-armani-manzara-store-2_533x.webp?v=1747500288'},
{id:'magnificent-gold',name:'YSL Magnificent Gold',price:null,priceLabel:'Price on request',category:'Unisex',notes:'White Oud · Vanilla',size:'75ml',stock:12,image:'https://www.faces.sa/dw/image/v2/BJSM_PRD/on/demandware.static/-/Sites-faces-master-catalog/default/dw83d3e8f3/product/3614271677617/3614271677617.jpg'},
{id:'ambre-levant',name:'Louis Vuitton Ambre Levant',price:null,priceLabel:'Price on request',category:'Unisex',notes:'Oud Wood · Amber · Mandarin · White Pepper',size:'100ml',stock:12,image:'https://www.crepslocker.com/cdn/shop/files/louis-vuitton-ambre-levant-eau-de-parfum-nvprod7160001v-front-with-bottle.webp?v=1773135129'},
{id:'gucci-bloom',name:'Gucci Bloom Eau de Parfum',price:null,priceLabel:'Price on request',category:'Women',notes:'Jasmine · Tuberose · Rangoon Creeper',size:'100ml',stock:12,image:'https://cdn.shopify.com/s/files/1/0008/4285/8551/files/100MLGUCCIBLOOMEAUDEPARFUM_1.jpg'},
{id:'kayali-vanilla-28',name:'KAYALI Vanilla | 28',price:null,priceLabel:'Price on request',category:'Women',notes:'Vanilla Orchid · Brown Sugar · Tonka · Amber',size:'100ml',stock:12,image:'https://fnf.co.ke/wp-content/uploads/Kayali-Vanilla-28-Eau-De-Parfum-100ml.jpg'},
{id:'kayali-candy-42',name:'KAYALI Vanilla Candy Rock Sugar | 42',price:null,priceLabel:'Price on request',category:'Women',notes:'Candied Pear · Bubble Gum · Vanilla Cream · Tonka',size:'100ml',stock:12,image:'https://app.mashuppos.com/media/0cd383e125b951fedc2c022a1457c13f/kayali-vanilla-candy-rock-sugar-42-50-100-ml-eau-de-parfum-20251111181520.jpg'},
{id:'lacoste-blanc',name:'Lacoste L.12.12 Blanc Eau de Toilette',price:null,priceLabel:'Price on request',category:'Men',notes:'Grapefruit · Cardamom · Vetiver · Suede',size:'100ml',stock:12,image:'https://product-images.metro.ca/images/h29/h8e/16386594471966.jpg'},
{id:'212-vip-black',name:'Carolina Herrera 212 VIP Black',price:null,priceLabel:'Price on request',category:'Men',notes:'Absinthe · Anise · Lavender · Black Vanilla · Musk',size:'100ml',stock:12,image:'https://f.nooncdn.com/p/pzsku/Z07C5AF7148C5717B1112Z/45/_/1778591796/e8136d58-334e-4e17-b42f-cc205bc9497c.jpg'},
{id:'bright-crystal',name:'Versace Bright Crystal EDT',price:null,priceLabel:'Price on request',category:'Women',notes:'Yuzu · Pomegranate · Peony · Magnolia · Musk',size:'200ml',stock:12,image:'https://f.nooncdn.com/p/pzsku/ZC0604DB283B5AB138353Z/45/_/1779704034/c783173b-5d9c-408d-806d-f4764be2fdce.jpg'},
{id:'libre-leau-nue',name:"YSL Libre L'Eau Nue",price:null,priceLabel:'Price on request',category:'Women',notes:'Green Mandarin · Bergamot · Orange Blossom · Lavender',size:'50ml',stock:12,image:'https://www.haar-shop.ch/media/catalog/product/1/e/1ec117fcf587856fbf5430fada46d7ce2eb0e650_3614274293845_bi_ysl_libre_l_eau_nue.jpg'},
{id:'bleu-edp',name:'Bleu de Chanel EDP',price:null,priceLabel:'Price on request',category:'Men',notes:'Citrus · Woods · Amber',size:'150ml',stock:12,image:'https://perfumes.ec/cdn/shop/files/ChanelBleuDeChanelEauDeParfum150ml.png?v=1700345265'},
{id:'bleu-parfum',name:'Bleu de Chanel Parfum',price:null,priceLabel:'Price on request',category:'Men',notes:'Citrus · Cedar · Sandalwood',size:'100ml',stock:12,image:'https://www.beyazitparfum.com/cache/large/product/771/M344.jpg'},
{id:'bleu-exclusif',name:"Bleu de Chanel L'Exclusif",price:null,priceLabel:'Price on request',category:'Men',notes:'Cedar · Amber · Leather · Resinous notes',size:'100ml',stock:12,image:'https://parfumstock.uz/thumb/2/86haw_YpPOSNGA1CqixXdA/750r750/d/bleu_de_chanel_lexc100-min-min.png'},
{id:'terre-hermes',name:"Terre d'Hermès Eau de Toilette",price:null,priceLabel:'Price on request',category:'Men',notes:'Grapefruit · Cedar · Flint · Vetiver',size:'50ml',stock:12,image:'https://ss701.liverpool.com.mx/xl/78267496.jpg'},
{id:'black-orchid',name:'Tom Ford Black Orchid Eau de Parfum',price:null,priceLabel:'Price on request',category:'Unisex',notes:'Black Orchid · Truffle · Patchouli · Vanilla',size:'100ml',stock:12,image:'https://f.nooncdn.com/p/pzsku/ZD74667586045F898DAA1Z/45/_/1779094688/31c7bf1b-b513-451f-af5e-6bb273d726bb.jpg'},
{id:'ysl-y-edt',name:'Y Eau de Toilette',price:null,priceLabel:'Price on request',category:'Men',notes:'Lavender · Geranium · Cedarwood · Incense',size:'100ml',stock:12,image:'https://product-images.metro.ca/images/hab/h71/16087166091294.jpg'}
];
let products=JSON.parse(localStorage.getItem('teeb_products')||'null');
const byId=new Map(DEFAULT_PRODUCTS.map(p=>[p.id,p]));
if(!Array.isArray(products)){products=DEFAULT_PRODUCTS.map(p=>({...p}));}
else{products=products.filter(p=>byId.has(p.id)).map(p=>({...byId.get(p.id),...p}));DEFAULT_PRODUCTS.forEach(p=>{if(!products.some(x=>x.id===p.id))products.push({...p})});}
localStorage.setItem('teeb_products',JSON.stringify(products));
const saveProducts=()=>localStorage.setItem('teeb_products',JSON.stringify(products));
const cart=()=>JSON.parse(localStorage.getItem('teeb_cart')||'[]');
const setCart=c=>{localStorage.setItem('teeb_cart',JSON.stringify(c));updateCartCount()};
const updateCartCount=()=>document.querySelectorAll('#cartCount').forEach(e=>e.textContent=cart().reduce((a,x)=>a+x.qty,0));
const getProduct=id=>products.find(p=>p.id===id);
const displayPrice=p=>p.price==null?(p.priceLabel||'Price on request'):`${p.price} JOD`;
function addToCart(id){let p=getProduct(id);if(!p||p.price==null)return alert('Price will be confirmed by TEEB.');let c=cart(),x=c.find(i=>i.id===id);x?x.qty++:c.push({id,qty:1});setCart(c);alert('Added to cart')}
function product_card(p){return `<article class="card"><div class="card-img" style="overflow:hidden;background:#fff"><img src="${p.image}" alt="${p.name}" style="width:100%;height:100%;object-fit:contain;border-radius:12px">${p.stock<=0?'<span class="sold">SOLD OUT</span>':''}</div><div class="eyebrow" style="margin-top:14px">${p.category} · ${p.size||'—'}</div><h3>${p.name}</h3><div class="notes">${p.notes}</div><div class="price-row"><span class="price">${displayPrice(p)}</span><span class="notes">${p.stock>0?p.stock+' in stock':'Unavailable'}</span></div>${p.stock>0&&p.price!=null?`<button class="btn btn-primary" onclick="addToCart('${p.id}')">ADD TO CART</button>`:p.stock>0?`<button class="btn btn-outline" onclick="alert('Price will be confirmed by TEEB.')">PRICE ON REQUEST</button>`:'<div class="status sold-status" style="display:block;margin-top:12px;text-align:center">SOLD OUT</div>'}<a class="btn btn-outline" style="width:100%;margin-top:8px" href="product.html?id=${p.id}">VIEW DETAILS</a></article>`}
function renderHome(){let e=document.getElementById('featured');if(e)e.innerHTML=products.slice(0,8).map(product_card).join('')}
function renderShop(){let e=document.getElementById('shopProducts');if(!e)return;let q=(document.getElementById('search')?.value||'').toLowerCase(),cat=document.getElementById('category')?.value||'All',stock=document.getElementById('inStock')?.checked,sort=document.getElementById('sort')?.value||'new',a=products.filter(p=>(p.name+p.notes).toLowerCase().includes(q)&&(cat==='All'||p.category===cat)&&(!stock||p.stock>0));if(sort==='low')a.sort((x,y)=>(x.price??999999)-(y.price??999999));if(sort==='high')a.sort((x,y)=>(y.price??-1)-(x.price??-1));e.innerHTML=a.map(product_card).join('')}
function renderProduct(){let e=document.getElementById('productPage');if(!e)return;let p=getProduct(new URLSearchParams(location.search).get('id'))||products[0];e.innerHTML=`<section class="product-detail"><div class="detail-image" style="padding:25px;background:#fff;overflow:hidden"><img src="${p.image}" alt="${p.name}" style="width:100%;height:100%;max-height:560px;object-fit:contain"></div><div class="detail"><div class="eyebrow">${p.category} · ${p.size||'—'} · TEEB</div><h1>${p.name}</h1><div class="notes" style="font-size:16px">${p.notes}</div><div class="bigprice">${displayPrice(p)}</div><p>Premium fragrance selected for the TEEB collection. A distinctive scent designed to leave a memorable impression.</p><hr><h4>Size</h4><div class="option-row"><button class="option selected">${p.size||'—'}</button></div>${p.price!=null?`<h4>Quantity</h4><div class="qty"><button onclick="changeQty(-1)">−</button><span id="qty">1</span><button onclick="changeQty(1)">+</button></div><button class="btn btn-primary" style="width:100%;margin-top:22px" onclick="addDetail('${p.id}')">ADD TO CART</button>`:`<button class="btn btn-primary" style="width:100%;margin-top:22px" onclick="alert('Price will be confirmed by TEEB.')">CONTACT FOR PRICE</button>`}<div class="card" style="margin-top:20px"><b>🚚 Free delivery over 50 JOD</b><br><span class="notes">Cash on delivery available across Jordan.</span></div></div></section>`}
function changeQty(n){let e=document.getElementById('qty');e.textContent=Math.max(1,+e.textContent+n)}
function addDetail(id){let p=getProduct(id);if(!p||p.price==null)return alert('Price will be confirmed by TEEB.');let q=+document.getElementById('qty').textContent,c=cart(),x=c.find(i=>i.id===id);x?x.qty+=q:c.push({id,qty:q});setCart(c);location.href='cart.html'}
function renderCart(){let e=document.getElementById('cartItems');if(!e)return;let c=cart();if(!c.length){e.innerHTML='<h2>Your cart is empty</h2><p class="notes">Browse our fragrances and find your signature scent.</p><a class="btn btn-primary" href="shop.html">SHOP FRAGRANCES</a>';return}e.innerHTML=c.map(i=>{let p=getProduct(i.id);return `<div class="cart-row"><div class="thumb"><img src="${p.image}" alt="" style="width:100%;height:100%;object-fit:contain"></div><div><b>${p.name}</b><div class="notes">${p.notes} · ${p.size||''}</div></div><div>${displayPrice(p)}</div><div class="qty"><button onclick="cartChange('${p.id}',-1)">−</button><span>${i.qty}</span><button onclick="cartChange('${p.id}',1)">+</button></div><button onclick="removeCart('${p.id}')" style="border:0;background:none;cursor:pointer">🗑</button></div>`}).join('');let sub=c.reduce((a,i)=>a+(getProduct(i.id).price||0)*i.qty,0),del=sub>=50?0:2;document.getElementById('cartSummary').innerHTML=`<h2>Order Summary</h2><div class="summary-line"><span>Subtotal</span><b>${sub.toFixed(2)} JOD</b></div><div class="summary-line"><span>Delivery</span><b>${del.toFixed(2)} JOD</b></div><div class="total">Total <span style="float:right">${(sub+del).toFixed(2)} JOD</span></div><button class="btn btn-primary" style="width:100%;margin-top:22px" onclick="location.href='checkout.html'">PROCEED TO CHECKOUT</button>`}
function cartChange(id,n){let c=cart(),x=c.find(i=>i.id===id);x.qty=Math.max(1,x.qty+n);setCart(c);renderCart()}
function removeCart(id){setCart(cart().filter(i=>i.id!==id));renderCart()}
function checkoutSummary(){let e=document.getElementById('checkoutSummary');if(!e)return;let c=cart(),sub=c.reduce((a,i)=>a+(getProduct(i.id).price||0)*i.qty,0),del=sub>=50?0:2;e.innerHTML='<h2>Order Summary</h2>'+c.map(i=>`<div class="summary-line"><span>${getProduct(i.id).name} × ${i.qty}</span><b>${((getProduct(i.id).price||0)*i.qty).toFixed(2)} JOD</b></div>`).join('')+`<div class="summary-line"><span>Delivery</span><b>${del.toFixed(2)} JOD</b></div><div class="total">Total <span style="float:right">${(sub+del).toFixed(2)} JOD</span></div>`}
function placeOrder(){if(!cart().length)return alert('Your cart is empty');alert('Order received! TEEB will contact you to confirm delivery.');setCart([]);location.href='index.html'}
function renderAdmin(){let e=document.getElementById('adminProducts');if(!e)return;e.innerHTML=products.map(p=>`<tr><td><div style="display:flex;align-items:center;gap:10px"><img src="${p.image}" alt="" style="width:45px;height:45px;object-fit:contain;background:#fff;border-radius:7px"><div><b>${p.name}</b><div class="notes">${p.notes} · ${p.size||''}</div></div></div></td><td>${p.category}</td><td>${displayPrice(p)}</td><td>${p.stock}</td><td><span class="status ${p.stock?'active-status':'sold-status'}">${p.stock?'Active':'Sold Out'}</span></td><td><button onclick="toggleStock('${p.id}')">↕</button> <button onclick="deleteProduct('${p.id}')">🗑</button></td></tr>`).join('');document.getElementById('adminProductCount').textContent=products.length;document.getElementById('adminSoldOut').textContent=products.filter(p=>!p.stock).length}
function toggleStock(id){let p=getProduct(id);p.stock=p.stock?0:10;saveProducts();renderAdmin()}
function deleteProduct(id){if(confirm('Delete this product?')){products=products.filter(p=>p.id!==id);saveProducts();renderAdmin()}}
document.addEventListener('DOMContentLoaded',()=>{updateCartCount();renderHome();renderShop();renderProduct();renderCart();checkoutSummary();renderAdmin();document.getElementById('search')?.addEventListener('input',renderShop);document.getElementById('category')?.addEventListener('change',renderShop);document.getElementById('sort')?.addEventListener('change',renderShop);document.getElementById('inStock')?.addEventListener('change',renderShop);document.querySelectorAll('.cat').forEach(x=>x.addEventListener('change',()=>{document.getElementById('category').value=x.checked?x.value:'All';renderShop()}));document.getElementById('adminSearch')?.addEventListener('input',renderAdmin)})